"""Update datatype of latest column

Revision ID: 9c3d27ac2b13
Revises: b8f84cf5f30c
Create Date: 2024-06-13 21:01:22.436802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9c3d27ac2b13'
down_revision: Union[str, None] = 'b8f84cf5f30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mach_employee',  'latest',type_=sa.String(),existing_type=sa.Boolean(),postgresql_using="latest::varchar"    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mach_employee',  'latest',type_=sa.Boolean(),existing_type=sa.String(),postgresql_using="latest::boolean"    )
    