"""Update datatype of latest column from Boolean to String

Revision ID: b8f84cf5f30c
Revises: fcac03c81619
Create Date: 2024-06-13 20:47:08.807918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f84cf5f30c'
down_revision: Union[str, None] = 'fcac03c81619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mach_employee', 'latest',existing_type=sa.Boolean,type= sa.String,existing_nullable=True,existing_server_default=sa.false)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mach_employee', 'latest',existing_type=sa.String,type= sa.Boolean,existing_nullable=True)
    # ### end Alembic commands ###
