from sqlalchemy import Column, Integer, Float, ForeignKey, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship, column_property
from db.base_class import Base
from db.session import engine
# Base.metadata.create_all(bind=engine)
class Skills1(Base):
    # __tablename__ = 'skills'
    user_id = Column(UUID(as_uuid=True), ForeignKey('mach_employee.user_id'), primary_key=True)
    python = column_property(Column("Python", Integer, nullable=True))     
    sql = column_property(Column("SQL", Integer, nullable=True))     
    excel = column_property(Column("Excel", Integer, nullable=True))     
    storyboarding = column_property(Column("Storyboarding", Integer, nullable=True))     
    business_communication = column_property(Column("Business Communication", Integer, nullable=True))     
    deck_making = column_property(Column("Deck Making", Integer, nullable=True))     
    r = column_property(Column("R", Integer, nullable=True))     
    java = column_property(Column("Java", Integer, nullable=True))     
    javascript = column_property(Column("Javascript", Integer, nullable=True))     
    shell_scripting = column_property(Column("Shell scripting", Integer, nullable=True))     
    ruby = column_property(Column("Ruby", Integer, nullable=True))     
    scala = column_property(Column("Scala", Integer, nullable=True))     
    go = column_property(Column("Go", Integer, nullable=True))     
    rust = column_property(Column("Rust", Integer, nullable=True))     
    exploratory_data_analysis = column_property(Column("Exploratory Data Analysis", Integer, nullable=True))    
    statistics = column_property(Column("Statistics", Integer, nullable=True))     
    bayesian_statistics = column_property(Column("Bayesian Statistics", Integer, nullable=True))     
    feature_engineering = column_property(Column("Feature Engineering", Integer, nullable=True))     
    feature_selection = column_property(Column("Feature Selection", Integer, nullable=True))     
    modelling_process = column_property(Column("Modelling Process", Integer, nullable=True))     
    causal_analysis_and_design_of_experiments = column_property(Column("Causal Analysis & Design of Experiments", Integer, nullable=True))     
    probability = column_property(Column("Probability", Integer, nullable=True))     
    linear_algebra = column_property(Column("Linear Algebra", Integer, nullable=True))     
    hyperparameters_tuning = column_property(Column("Hyperparameters Tuning", Integer, nullable=True))     
    dimensionality_reduction = column_property(Column("Dimensionality Reduction", Integer, nullable=True))     
    regression = column_property(Column("Regression", Integer, nullable=True))     
    clustering = column_property(Column("Clustering", Integer, nullable=True))     
    time_series_analysis = column_property(Column("Time Series Analysis", Integer, nullable=True))     
    classification = column_property(Column("Classification", Integer, nullable=True))     
    nlp = column_property(Column("NLP", Integer, nullable=True))     
    neural_networks = column_property(Column("Neural Networks", Integer, nullable=True))     
    computer_vision = column_property(Column("Computer Vision", Integer, nullable=True))     
    reinforcement_learning = column_property(Column("Reinforcement Learning", Integer, nullable=True))     
    operations_research = column_property(Column("Operations Research", Integer, nullable=True))     
    self_supervised_learning = column_property(Column("Self-Supervised Learning", Integer, nullable=True))     
    graph_machine_learning = column_property(Column("Graph Machine Learning", Integer, nullable=True))     
    ethics_in_ai_and_ml = column_property(Column("Ethics in AI & ML", Integer, nullable=True))     
    information_extraction = column_property(Column("Information Extraction", Integer, nullable=True))     
    anomaly_detection = column_property(Column("Anomaly detection", Integer, nullable=True))     
    clustering_theory = column_property(Column("Clustering theory", Integer, nullable=True))     
    knowledge_graphs = column_property(Column("Knowledge Graphs", Integer, nullable=True))     
    optimization = column_property(Column("Optimization", Integer, nullable=True))     
    tableau = column_property(Column("Tableau", Integer, nullable=True))    
    powerbi = column_property(Column("PowerBi", Integer, nullable=True))     
    looker = column_property(Column("Looker", Integer, nullable=True))     
    rshiny = column_property(Column("Rshiny", Integer, nullable=True))     
    microstrategy = column_property(Column("Microstrategy", Integer, nullable=True))     
    grafana = column_property(Column("Grafana", Integer, nullable=True))     
    qlikview = column_property(Column("QlikView", Integer, nullable=True))     
    qliksense = column_property(Column("QlikSense", Integer, nullable=True))     
    aws_quicksight = column_property(Column("AWS QuickSight", Integer, nullable=True))    
    aws = column_property(Column("AWS", Integer, nullable=True))     
    azure = column_property(Column("Azure", Integer, nullable=True))     
    gcp = column_property(Column("GCP", Integer, nullable=True))     
    design_thinking = column_property(Column("Design Thinking", Integer, nullable=True))     
    sdlc_process = column_property(Column("SDLC process", Integer, nullable=True))     
    testing_lifecycle = column_property(Column("Testing LifeCycle", Integer, nullable=True))     
    project_management = column_property(Column("Project Management", Integer, nullable=True))     
    requirements_gathering = column_property(Column("Requirements Gathering", Integer, nullable=True))     
    rally = column_property(Column("Rally", Integer, nullable=True))     
    agile_model_of_development = column_property(Column("Agile model of development", Integer, nullable=True))     
    fast_api = column_property(Column("FAST API", Integer, nullable=True))     
    flask = column_property(Column("Flask", Integer, nullable=True))     
    angular = column_property(Column("Angular", Integer, nullable=True))     
    html_css = column_property(Column("HTML/CSS", Integer, nullable=True))     
    nodejs = column_property(Column("NodeJS", Integer, nullable=True))     
    go_lang = column_property(Column("Go Lang", Integer, nullable=True))     
    django = column_property(Column("Django", Integer, nullable=True))     
    next_js = column_property(Column("Next JS", Integer, nullable=True))    
    vue_js = column_property(Column("Vue JS", Integer, nullable=True))     
    react_js = column_property(Column("React JS", Integer, nullable=True))     
    argocd = column_property(Column("ArgoCD", Integer, nullable=True))     
    azure_devops = column_property(Column("Azure DevOps", Integer, nullable=True))     
    github = column_property(Column("GitHub", Integer, nullable=True))     
    gitlab = column_property(Column("GitLab", Integer, nullable=True))     
    gocd = column_property(Column("GoCD", Integer, nullable=True))     
    gcp_cloud_build = column_property(Column("GCP Cloud Build", Integer, nullable=True))     
    jenkins = column_property(Column("Jenkins", Integer, nullable=True))     
    aws_codepipeline_codebuild_codedeploy = column_property(Column("AWS (CodePipeline, CodeBuild, CodeDeploy)", Integer, nullable=True))     
    informatica = column_property(Column("Informatica", Integer, nullable=True))     
    talend = column_property(Column("Talend", Integer, nullable=True))     
    pentaho = column_property(Column("Pentaho", Integer, nullable=True))     
    ssis = column_property(Column("SSIS", Integer, nullable=True))     
    airbyte = column_property(Column("AirByte", Integer, nullable=True))     
    nifi2 = column_property(Column("NiFi2", Integer, nullable=True))     
    fivetran = column_property(Column("Fivetran", Integer, nullable=True))     
    matillion = column_property(Column("Matillion", Integer, nullable=True))     
    airflow = column_property(Column("Airflow", Integer, nullable=True))     
    aws_glue = column_property(Column("AWS Glue", Integer, nullable=True))     
    aws_step_functions = column_property(Column("AWS Step Functions", Integer, nullable=True))     
    azure_data_factory = column_property(Column("Azure Data Factory", Integer, nullable=True))     
    google_cloud_composer = column_property(Column("Google Cloud Composer", Integer, nullable=True))     
    nifi = column_property(Column("Nifi", Integer, nullable=True))     
    oozie = column_property(Column("Oozie", Integer, nullable=True))     
    data_modelling = column_property(Column("Data Modelling", Integer, nullable=True))     
    system_architecture_design = column_property(Column("System Architecture Design", Integer, nullable=True))     
    network_architecture_design = column_property(Column("Network Architecture Design", Integer, nullable=True))     
    databricks = column_property(Column("Databricks", Integer, nullable=True))     
    datalake_s3_adls_gcs = column_property(Column("Datalake (S3, ADLS, GCS)", Integer, nullable=True))     
    batch_data_pipeline = column_property(Column("Batch Data pipeline", Integer, nullable=True))     
    streaming_data_pipeline = column_property(Column("Streaming Data Pipeline", Integer, nullable=True))     
    data_storage = column_property(Column("Data Storage", Integer, nullable=True))     
    azure_sql_db = column_property(Column("Azure SQL DB", Integer, nullable=True))     
    db2 = column_property(Column("DB2", Integer, nullable=True))     
    mysql = column_property(Column("MySQL", Integer, nullable=True))     
    oracle = column_property(Column("Oracle", Integer, nullable=True))     
    sql_server = column_property(Column("SQL Server", Integer, nullable=True))     
    postgresql = column_property(Column("PostgreSQL", Integer, nullable=True))     
    hive2 = column_property(Column("Hive2", Integer, nullable=True))     
    azure_synapse_analysis = column_property(Column("Azure Synapse Analysis", Integer, nullable=True))     
    google_bigquery = column_property(Column("Google BigQuery", Integer, nullable=True))     
    aws_redshift = column_property(Column("AWS Redshift", Integer, nullable=True))     
    snowflake = column_property(Column("Snowflake", Integer, nullable=True))     
    mongodb = column_property(Column("MongoDB", Integer, nullable=True))     
    couchbase = column_property(Column("CouchBase", Integer, nullable=True))     
    azure_cosmos_db = column_property(Column("Azure Cosmos DB", Integer, nullable=True))     
    aws_dynamodb = column_property(Column("AWS DynamoDB", Integer, nullable=True))     
    gcp_firestore_bigtable = column_property(Column("GCP Firestore/BigTable", Integer, nullable=True))     
    hbase = column_property(Column("Hbase", Integer, nullable=True))     
    hadoop = column_property(Column("Hadoop", Integer, nullable=True))     
    hive = column_property(Column("Hive", Integer, nullable=True))     
    pig = column_property(Column("Pig", Integer, nullable=True))     
    kafka = column_property(Column("Kafka", Integer, nullable=True))     
    pyspark = column_property(Column("PySpark", Integer, nullable=True))     
    sqoop = column_property(Column("Sqoop", Integer, nullable=True))     
    iot = column_property(Column("IOT", Integer, nullable=True))     
    docker = column_property(Column("Docker", Integer, nullable=True))     
    terraform = column_property(Column("Terraform", Integer, nullable=True))     
    kubernetes = column_property(Column("Kubernetes", Integer, nullable=True))     
    podman = column_property(Column("Podman", Integer, nullable=True))     
    ansible = column_property(Column("Ansible", Integer, nullable=True))     
    chef = column_property(Column("Chef", Integer, nullable=True))     
    azure_bicep = column_property(Column("Azure Bicep", Integer, nullable=True))     
    azure_arm = column_property(Column("Azure ARM", Integer, nullable=True))     
    adobe_analytics = column_property(Column("Adobe Analytics", Integer, nullable=True))     
    matomo = column_property(Column("Matomo", Integer, nullable=True))     
    google_analytics = column_property(Column("Google Analytics", Integer, nullable=True))     
    azure_ml_studio = column_property(Column("Azure ML Studio", Integer, nullable=True))     
    aws_sagemaker = column_property(Column("AWS Sagemaker", Integer, nullable=True))     
    dataiku = column_property(Column("Dataiku", Integer, nullable=True))     
    datarobot = column_property(Column("DataRobot", Integer, nullable=True))     
    gcp_vertex_ai = column_property(Column("GCP Vertex AI", Integer, nullable=True))     
    mlflow = column_property(Column("MLFlow", Integer, nullable=True))     
    kubeflow = column_property(Column("Kubeflow", Integer, nullable=True))     
    seldon_core = column_property(Column("Seldon Core", Integer, nullable=True))     
    fiddler = column_property(Column("Fiddler", Integer, nullable=True))     
    bentoml = column_property(Column("BentoML", Integer, nullable=True))     
    bdd = column_property(Column("BDD", Integer, nullable=True))     
    tdd = column_property(Column("TDD", Integer, nullable=True))     
    postman = column_property(Column("Postman", Integer, nullable=True))     
    sonarqube = column_property(Column("SonarQube", Integer, nullable=True))     
    jmeter = column_property(Column("Jmeter", Integer, nullable=True))     
    cucumber = column_property(Column("Cucumber", Integer, nullable=True))     
    testrail = column_property(Column("TestRail", Integer, nullable=True)) 
    pytest_unittest = column_property(Column("Pytest/unittest", Integer, nullable=True)) 
    mocha_chai = column_property(Column("Mocha/Chai", Integer, nullable=True)) 
    jasmine = column_property(Column("Jasmine", Integer, nullable=True)) 
    alation = column_property(Column("Alation", Integer, nullable=True)) 
    atlan = column_property(Column("Atlan", Integer, nullable=True)) 
    azure_purview = column_property(Column("Azure Purview", Integer, nullable=True)) 
    great_expectations = column_property(Column("Great Expectations", Integer, nullable=True)) 
    collibra = column_property(Column("Collibra", Integer, nullable=True)) 
    adls_gen2 = column_property(Column("ADLS Gen2", Integer, nullable=True)) 
    aws_s3 = column_property(Column("AWS S3", Integer, nullable=True)) 
    hdfs = column_property(Column("HDFS", Integer, nullable=True)) 
    gcp_cloud_storage = column_property(Column("GCP Cloud Storage", Integer, nullable=True)) 
    redis = column_property(Column("Redis", Integer, nullable=True)) 
    memcached = column_property(Column("Memcached", Integer, nullable=True)) 
    apache_beam = column_property(Column("Apache Beam", Integer, nullable=True)) 
    apache_flink = column_property(Column("Apache Flink", Integer, nullable=True)) 
    spark_streaming = column_property(Column("Spark Streaming", Integer, nullable=True)) 
    gcp_dataflow = column_property(Column("GCP Dataflow", Integer, nullable=True)) 
    gcp_pub_sub = column_property(Column("GCP Pub-Sub", Integer, nullable=True)) 
    azure_event_hub = column_property(Column("Azure Event Hub", Integer, nullable=True)) 
    aws_kinesis = column_property(Column("AWS Kinesis", Integer, nullable=True)) 
    azure_stream_analytics = column_property(Column("Azure Stream Analytics", Integer, nullable=True)) 
    apache_kafka = column_property(Column("Apache Kafka", Integer, nullable=True)) 
    ux_research = column_property(Column("UX research", Integer, nullable=True)) 
    ux_design = column_property(Column("UX design", Integer, nullable=True)) 
    ui_design = column_property(Column("UI design", Integer, nullable=True)) 
    prototyping = column_property(Column("Prototyping", Integer, nullable=True)) 
    video_creation = column_property(Column("Video creation", Integer, nullable=True)) 
    ux_writing = column_property(Column("UX writing", Integer, nullable=True)) 
    graphic_design = column_property(Column("Graphic Design", Integer, nullable=True)) 
    value_communication_design = column_property(Column("Value Communication Design", Integer, nullable=True)) 
    figma = column_property(Column("Figma", Integer, nullable=True)) 
    adobe_illustrator = column_property(Column("Adobe Illustrator", Integer, nullable=True)) 
    adobe_photoshop = column_property(Column("Adobe Photoshop", Integer, nullable=True)) 
    adobe_premier_pro = column_property(Column("Adobe Premier Pro", Integer, nullable=True)) 
    adobe_after_effects = column_property(Column("Adobe After Effects", Integer, nullable=True)) 
    automobile = column_property(Column("Automobile", Integer, nullable=True)) 
    banking = column_property(Column("Banking", Integer, nullable=True)) 
    cpg = column_property(Column("CPG", Integer, nullable=True)) 
    hospitality = column_property(Column("Hospitality", Integer, nullable=True)) 
    insurance = column_property(Column("Insurance", Integer, nullable=True)) 
    healthcare_and_pharma = column_property(Column("Healthcare & Pharma", Integer, nullable=True)) 
    retail = column_property(Column("Retail", Integer, nullable=True)) 
    technology = column_property(Column("Technology", Integer, nullable=True)) 
    renewable_energy = column_property(Column("Renewable Energy", Integer, nullable=True)) 
    telecom = column_property(Column("Telecom", Integer, nullable=True)) 
    strategy_and_planning = column_property(Column("Strategy & Planning", Integer, nullable=True)) 
    pricing_and_revenue_management = column_property(Column("Pricing & Revenue Management", Integer, nullable=True)) 
    growth_marketing_and_sales = column_property(Column("Growth, Marketing & Sales", Integer, nullable=True)) 
    logistics_and_supply_chain = column_property(Column("Logistics & Supply Chain", Integer, nullable=True)) 
    merchandising_and_store_ops = column_property(Column("Merchandising & Store Ops", Integer, nullable=True)) 
    digital = column_property(Column("Digital", Integer, nullable=True)) 
    consumer_insights = column_property(Column("Consumer Insights", Integer, nullable=True)) 
    deep_learning = column_property(Column("Deep Learning", Integer, nullable=True)) 
    agile_scrum = column_property(Column("Agile: Scrum", Integer, nullable=True)) 
    agile_kanban = column_property(Column("Agile: Kanban", Integer, nullable=True)) 
    pm_tools_jira = column_property(Column("PM Tools: JIRA", Integer, nullable=True)) 
    gcp_pub_sub = column_property(Column("GCP Pub/Sub", Integer, nullable=True)) 
    scrum = column_property(Column("scrum", Integer, nullable=True)) 
    application_ci_cd = column_property(Column("Application CI/CD", Integer, nullable=True)) 
    etl___elt = column_property(Column("ETL / ELT", Integer, nullable=True)) 
    asp_skills = column_property(Column("asp_skills", Integer, nullable=True)) 
    discipline_and_integrity = column_property(Column("Discipline & Integrity", Integer, nullable=True)) 
    initiative_and_ownership = column_property(Column("Initiative & Ownership", Integer, nullable=True)) 
    adaptability = column_property(Column("Adaptability", Integer, nullable=True)) 
    teamwork = column_property(Column("Teamwork", Integer, nullable=True)) 
    innovative_thinking = column_property(Column("Innovative Thinking", Integer, nullable=True)) 
    curiosity_and_learning_agility = column_property(Column("Curiosity & Learning Agility", Integer, nullable=True)) 
    problem_solving = column_property(Column("Problem Solving", Integer, nullable=True)) 
    result_orientation = column_property(Column("Result Orientation", Integer, nullable=True)) 
    quality_focus = column_property(Column("Quality Focus", Integer, nullable=True)) 
    effective_communication = column_property(Column("Effective Communication", Integer, nullable=True)) 
    work_management_and_effectiveness = column_property(Column("Work Management and effectiveness", Integer, nullable=True)) 
    clientcentric = column_property(Column("ClientCentric", Integer, nullable=True)) 
    genai = column_property(Column("GenAI", Integer, nullable=True)) 
    nuclios = column_property(Column("NucliOS", Integer, nullable=True))
    employee = relationship("MACH_Employee", back_populates="skills")